version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "weekly"
      cooldown:
        default-days: 7
    - package-ecosystem: "npm"
      directory: "/"
      ignore:
        - dependency-name: "eslint"
          versions: [">=10.0.0"]
      schedule:
        interval: "weekly"
      cooldown:
        default-days: 7
